version: '3'

services:
  nxtpopdnode0:
    container_name: nxtpopdnode0
    image: 'tendermint/nxtpopdnode'
    ports:
      - '26656-26657:26656-26657'
    environment:
      - ID=0
      - LOG=${LOG:-nxtpopd.log}
    volumes:
      - ./build:/nxtpopd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  nxtpopdnode1:
    container_name: nxtpopdnode1
    image: 'tendermint/nxtpopdnode'
    ports:
      - '26659-26660:26656-26657'
    environment:
      - ID=1
      - LOG=${LOG:-nxtpopd.log}
    volumes:
      - ./build:/nxtpopd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  nxtpopdnode2:
    container_name: nxtpopdnode2
    image: 'tendermint/nxtpopdnode'
    environment:
      - ID=2
      - LOG=${LOG:-nxtpopd.log}
    ports:
      - '26661-26662:26656-26657'
    volumes:
      - ./build:/nxtpopd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  nxtpopdnode3:
    container_name: nxtpopdnode3
    image: 'tendermint/nxtpopdnode'
    environment:
      - ID=3
      - LOG=${LOG:-nxtpopd.log}
    ports:
      - '26663-26664:26656-26657'
    volumes:
      - ./build:/nxtpopd:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
