version: "3"

services:
  teritoridnode0:
    container_name: teritoridnode0
    image: "tendermint/teritoridnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-teritorid.log}
    volumes:
      - ./build:/teritorid:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  teritoridnode1:
    container_name: teritoridnode1
    image: "tendermint/teritoridnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-teritorid.log}
    volumes:
      - ./build:/teritorid:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  teritoridnode2:
    container_name: teritoridnode2
    image: "tendermint/teritoridnode"
    environment:
      - ID=2
      - LOG=${LOG:-teritorid.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/teritorid:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  teritoridnode3:
    container_name: teritoridnode3
    image: "tendermint/teritoridnode"
    environment:
      - ID=3
      - LOG=${LOG:-teritorid.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/teritorid:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
